game_cym4: LoseScreen Class Reference
LoseScreen Class Reference
Public Member Functions
Scene init (Stage s, int width, int height)
Private Attributes
Group myRoot
Scene myScene
Menu myMenu
Static Private Attributes
static final int NUM_FRAMES_PER_SECOND = 60
Detailed Description
Definition at line 16 of file LoseScreen.java.
Member Function Documentation
Scene LoseScreen.init (Stage s, int width, int height)
Definition at line 24 of file LoseScreen.java.
References Menu.init(), and myScene.
Referenced by ItemBoxWorld.loseGame(), and BoxWorld.loseGame().
Member Data Documentation
Menu LoseScreen.myMenu private
Definition at line 20 of file LoseScreen.java.
Group LoseScreen.myRoot private
Definition at line 18 of file LoseScreen.java.
Scene LoseScreen.myScene private
Definition at line 19 of file LoseScreen.java.
Referenced by init().
final int LoseScreen.NUM_FRAMES_PER_SECOND = 60 static private
Definition at line 22 of file LoseScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_cym4/repository/StickyBox/src/LoseScreen.java