game_cym4: ItemBoxWorld Class Reference
ItemBoxWorld Class Reference
Public Member Functions
Scene init (Stage s, int width, int height)
Public Member Functions inherited from BoxWorld
Scene init (Stage s, int width, int height)
void createObstacleArray (int[] xCoord, int[] yCoord)
KeyFrame start (int frameRate)
void updateSprites ()
boolean onScreen (Node object)
Protected Member Functions
boolean checkAllCollisions ()
void winLevel ()
void handleKeyInput (KeyEvent e)
void reset ()
Protected Member Functions inherited from BoxWorld
Scene createScene (int width, int height)
void addStarterObjects ()
boolean checkAllCollisions ()
void winLevel ()
void loseGame ()
boolean checkCollide (ImageView obstacle)
void handleKeyInput (KeyEvent e)
void reset ()
void handleKeyRelease (KeyEvent e)
void setRoot (Group group)
Group getRoot ()
void setObstacleYCoordinates (int[] yCoords)
void setObstacleXCoordinates (int[] xCoords)
void setStage (Stage s)
Stage getStage ()
StickyBox getPlayer ()
Timeline getAnimation ()
void setAnimation (Timeline animate)
Private Member Functions
void addAllItems ()
ImageView addSingleItem (int xCoord, int yCoord)
boolean itemExists (Node item)
Private Attributes
Text myWarning
int itemCounter
ImageView myItem1
ImageView myItem2
Static Private Attributes
static final int NUM_OF_ITEMS = 2
Additional Inherited Members
Protected Attributes inherited from BoxWorld
int myWidth
int myHeight
Static Protected Attributes inherited from BoxWorld
static final int OBSTACLE_SIZE = 40
static final int NUM_FRAMES_PER_SECOND = 60
Detailed Description
This is the a class for a StickyBox level with items
Author
Callie Mao
Definition at line 21 of file ItemBoxWorld.java.
Member Function Documentation
void ItemBoxWorld.addAllItems () private
Puts all items onto the game screen
Definition at line 58 of file ItemBoxWorld.java.
References addSingleItem(), itemExists(), and NUM_OF_ITEMS.
Referenced by init(), and reset().
ImageView ItemBoxWorld.addSingleItem (int xCoord, int yCoord) private
Definition at line 68 of file ItemBoxWorld.java.
References BoxWorld.getRoot(), and BoxWorld.OBSTACLE_SIZE.
Referenced by addAllItems().
boolean ItemBoxWorld.checkAllCollisions () protected
Reduces item counter if StickyBox and removes item from game screen if StickyBox collides with it
Definition at line 83 of file ItemBoxWorld.java.
References BoxWorld.checkCollide(), BoxWorld.getRoot(), and itemExists().
void ItemBoxWorld.handleKeyInput (KeyEvent e) protected
Definition at line 129 of file ItemBoxWorld.java.
References winLevel().
Scene ItemBoxWorld.init (Stage s, int width, int height)
Definition at line 31 of file ItemBoxWorld.java.
References addAllItems(), BoxWorld.addStarterObjects(), BoxWorld.createScene(), BoxWorld.getAnimation(), BoxWorld.myHeight, BoxWorld.myWidth, BoxWorld.NUM_FRAMES_PER_SECOND, BoxWorld.setAnimation(), BoxWorld.setObstacleXCoordinates(), BoxWorld.setObstacleYCoordinates(), BoxWorld.setRoot(), BoxWorld.setStage(), and BoxWorld.start().
Referenced by BoxWorld.winLevel().
boolean ItemBoxWorld.itemExists (Node item) private
Returns
true if item is located on the game screen
Definition at line 98 of file ItemBoxWorld.java.
References BoxWorld.getRoot().
Referenced by addAllItems(), checkAllCollisions(), and winLevel().
void ItemBoxWorld.reset () protected
Definition at line 138 of file ItemBoxWorld.java.
References addAllItems().
void ItemBoxWorld.winLevel () protected
Definition at line 107 of file ItemBoxWorld.java.
References BoxWorld.getAnimation(), BoxWorld.getRoot(), BoxWorld.getStage(), EndScreen.init(), itemExists(), BoxWorld.myHeight, and BoxWorld.myWidth.
Referenced by handleKeyInput().
Member Data Documentation
int ItemBoxWorld.itemCounter private
Definition at line 24 of file ItemBoxWorld.java.
ImageView ItemBoxWorld.myItem1 private
Definition at line 25 of file ItemBoxWorld.java.
ImageView ItemBoxWorld.myItem2 private
Definition at line 26 of file ItemBoxWorld.java.
Text ItemBoxWorld.myWarning private
Definition at line 23 of file ItemBoxWorld.java.
final int ItemBoxWorld.NUM_OF_ITEMS = 2 static private
Definition at line 28 of file ItemBoxWorld.java.
Referenced by addAllItems().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_cym4/repository/StickyBox/src/ItemBoxWorld.java