game_cym4: BoxWorld Class Reference
BoxWorld Class Reference
Public Member Functions
Scene init (Stage s, int width, int height)
void createObstacleArray (int[] xCoord, int[] yCoord)
KeyFrame start (int frameRate)
void updateSprites ()
boolean onScreen (Node object)
Protected Member Functions
Scene createScene (int width, int height)
void addStarterObjects ()
boolean checkAllCollisions ()
void winLevel ()
void loseGame ()
boolean checkCollide (ImageView obstacle)
void handleKeyInput (KeyEvent e)
void reset ()
void handleKeyRelease (KeyEvent e)
void setRoot (Group group)
Group getRoot ()
void setObstacleYCoordinates (int[] yCoords)
void setObstacleXCoordinates (int[] xCoords)
void setStage (Stage s)
Stage getStage ()
StickyBox getPlayer ()
Timeline getAnimation ()
void setAnimation (Timeline animate)
Protected Attributes
int myWidth
int myHeight
Static Protected Attributes
static final int OBSTACLE_SIZE = 40
static final int NUM_FRAMES_PER_SECOND = 60
Private Member Functions
boolean allowMovement (int x, int y)
Private Attributes
Scene myScene
Group myRoot
ImageView myExit
Timeline myAnimation
Stage myStage
StickyBox myPlayer
int[] obstacleXCoordinates
int[] obstacleYCoordinates
ImageView[] obstacleArray
Static Private Attributes
static final int PLAYER_SPEED = 10
static final int RIGHT = 1
static final int LEFT = -1
static final int UP = 1
static final int DOWN = -1
static final int EXIT_COORDINATES = 320
static final int NUM_HINT_OBSTACLES = 7
Detailed Description
This is the primary level class for StickyBox.
Author
Callie Mao
Definition at line 21 of file BoxWorld.java.
Member Function Documentation
void BoxWorld.addStarterObjects () protected
Adds sticky box, obstacles, and the final exit to the game screen
Definition at line 86 of file BoxWorld.java.
References createObstacleArray().
Referenced by ItemBoxWorld.init(), and init().
boolean BoxWorld.allowMovement (int x, int y) private
Checks if Sticky Box can respond to a specific user input.
Returns
true when Sticky Box is not moving and if the current direction input is different from that of the previous input (to ensure the box does not go through an obstacle); returns false otherwise
Definition at line 289 of file BoxWorld.java.
References StickyBox.getXDirection(), StickyBox.getXPrev(), StickyBox.getYDirection(), and StickyBox.getYPrev().
Referenced by handleKeyInput().
boolean BoxWorld.checkAllCollisions () protected
Iterates through all obstacles and checks if the player has collided with any. Advances to win screen if player collides with the exit and to the lose screen if player is not one screen
Returns
true if player has collided with any other obstacles and false otherwise
Definition at line 169 of file BoxWorld.java.
References checkCollide(), loseGame(), onScreen(), and winLevel().
Referenced by updateSprites().
boolean BoxWorld.checkCollide (ImageView obstacle) protected
Checks if myPlayer has collided with a specific obstacle based on myPlayer's movement direction and its x-coordinates and y-coordinates relative to the obstacle's
Returns
true if player has collided with obstacle and false otherwise
Definition at line 207 of file BoxWorld.java.
References StickyBox.getXDirection(), and StickyBox.getYDirection().
Referenced by ItemBoxWorld.checkAllCollisions(), and checkAllCollisions().
void BoxWorld.createObstacleArray (int[] xCoord, int[] yCoord)
Uses the given x-coordinates and y-coordinates to construct and place obstacles onto the game screen
Definition at line 113 of file BoxWorld.java.
Referenced by addStarterObjects().
Scene BoxWorld.createScene (int width, int height) protected
Definition at line 75 of file BoxWorld.java.
References handleKeyInput(), handleKeyRelease(), and myScene.
Referenced by ItemBoxWorld.init(), and init().
Timeline BoxWorld.getAnimation () protected
Definition at line 342 of file BoxWorld.java.
References myAnimation.
Referenced by ItemBoxWorld.init(), and ItemBoxWorld.winLevel().
StickyBox BoxWorld.getPlayer () protected
Definition at line 338 of file BoxWorld.java.
References myPlayer.
Group BoxWorld.getRoot () protected
Definition at line 318 of file BoxWorld.java.
References myRoot.
Referenced by ItemBoxWorld.addSingleItem(), ItemBoxWorld.checkAllCollisions(), ItemBoxWorld.itemExists(), and ItemBoxWorld.winLevel().
Stage BoxWorld.getStage () protected
Definition at line 334 of file BoxWorld.java.
References myStage.
Referenced by ItemBoxWorld.winLevel().
void BoxWorld.handleKeyInput (KeyEvent e) protected
What to do each time a key is pressed
Definition at line 240 of file BoxWorld.java.
References allowMovement(), NUM_HINT_OBSTACLES, reset(), StickyBox.setDirection(), and winLevel().
Referenced by createScene().
void BoxWorld.handleKeyRelease (KeyEvent e) protected
Definition at line 303 of file BoxWorld.java.
References NUM_HINT_OBSTACLES.
Referenced by createScene().
Scene BoxWorld.init (Stage s, int width, int height)
Create the game's scene
Definition at line 53 of file BoxWorld.java.
References addStarterObjects(), createScene(), and start().
Referenced by Menu.init().
void BoxWorld.loseGame () protected
Definition at line 191 of file BoxWorld.java.
References LoseScreen.init().
Referenced by checkAllCollisions().
boolean BoxWorld.onScreen (Node object)
Checks if the passed in object parameter is within the game screen's bounds
Returns
true if object is on the screen and false if otherwise
Definition at line 155 of file BoxWorld.java.
Referenced by checkAllCollisions().
void BoxWorld.reset () protected
Resets the level by returning StickyBox back to its initial location in the top left corner
Definition at line 275 of file BoxWorld.java.
References StickyBox.setDirection(), and StickyBox.setPreviousDirection().
Referenced by handleKeyInput().
void BoxWorld.setAnimation (Timeline animate) protected
Definition at line 346 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
void BoxWorld.setObstacleXCoordinates (int[] xCoords) protected
Definition at line 326 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
void BoxWorld.setObstacleYCoordinates (int[] yCoords) protected
Definition at line 322 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
void BoxWorld.setRoot (Group group) protected
Definition at line 314 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
void BoxWorld.setStage (Stage s) protected
Definition at line 330 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
KeyFrame BoxWorld.start (int frameRate)
Create the game's frame
Definition at line 127 of file BoxWorld.java.
References updateSprites().
Referenced by ItemBoxWorld.init(), and init().
void BoxWorld.updateSprites ()
What to do each game frame: checks for collisions and moves the player
Definition at line 136 of file BoxWorld.java.
References checkAllCollisions(), StickyBox.getXDirection(), StickyBox.getYDirection(), StickyBox.isStuck, StickyBox.move(), StickyBox.setDirection(), StickyBox.setPreviousDirection(), and StickyBox.setStuck().
Referenced by start().
void BoxWorld.winLevel () protected
Definition at line 182 of file BoxWorld.java.
References ItemBoxWorld.init().
Referenced by checkAllCollisions(), and handleKeyInput().
Member Data Documentation
final int BoxWorld.DOWN = -1 static private
Definition at line 29 of file BoxWorld.java.
final int BoxWorld.EXIT_COORDINATES = 320 static private
Definition at line 46 of file BoxWorld.java.
final int BoxWorld.LEFT = -1 static private
Definition at line 27 of file BoxWorld.java.
Timeline BoxWorld.myAnimation private
Definition at line 34 of file BoxWorld.java.
Referenced by getAnimation().
ImageView BoxWorld.myExit private
Definition at line 33 of file BoxWorld.java.
int BoxWorld.myHeight protected
Definition at line 43 of file BoxWorld.java.
Referenced by ItemBoxWorld.init(), and ItemBoxWorld.winLevel().
StickyBox BoxWorld.myPlayer private
Definition at line 36 of file BoxWorld.java.
Referenced by getPlayer().
Group BoxWorld.myRoot private
Definition at line 32 of file BoxWorld.java.
Referenced by getRoot().
Scene BoxWorld.myScene private
Definition at line 31 of file BoxWorld.java.
Referenced by createScene().
Stage BoxWorld.myStage private
Definition at line 35 of file BoxWorld.java.
Referenced by getStage().
int BoxWorld.myWidth protected
Definition at line 42 of file BoxWorld.java.
Referenced by ItemBoxWorld.init(), and ItemBoxWorld.winLevel().
final int BoxWorld.NUM_FRAMES_PER_SECOND = 60 static protected
Definition at line 24 of file BoxWorld.java.
Referenced by ItemBoxWorld.init().
final int BoxWorld.NUM_HINT_OBSTACLES = 7 static private
Definition at line 48 of file BoxWorld.java.
Referenced by handleKeyInput(), and handleKeyRelease().
final int BoxWorld.OBSTACLE_SIZE = 40 static protected
Definition at line 23 of file BoxWorld.java.
Referenced by ItemBoxWorld.addSingleItem().
ImageView [] BoxWorld.obstacleArray private
Definition at line 40 of file BoxWorld.java.
int [] BoxWorld.obstacleXCoordinates private
Definition at line 38 of file BoxWorld.java.
int [] BoxWorld.obstacleYCoordinates private
Definition at line 39 of file BoxWorld.java.
final int BoxWorld.PLAYER_SPEED = 10 static private
Definition at line 22 of file BoxWorld.java.
final int BoxWorld.RIGHT = 1 static private
Definition at line 26 of file BoxWorld.java.
final int BoxWorld.UP = 1 static private
Definition at line 28 of file BoxWorld.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_cym4/repository/StickyBox/src/BoxWorld.java