game_cym4: StickyBox Class Reference
StickyBox Class Reference
Public Member Functions
StickyBox (int xPos, int yPos, int xSize, int ySize, int speed, int movingXDirect, int movingYDirect, boolean stuck)
boolean isStuck ()
void setStuck (boolean stuck)
void setDirection (int x, int y)
void setPreviousDirection (int x, int y)
int getXPrev ()
int getYPrev ()
int getXDirection ()
int getYDirection ()
void move ()
int getSpeed ()
Private Attributes
int xMove
int yMove
int mySpeed
boolean isStuck
int xPrev
int yPrev
Detailed Description
This is the class that defines the properties of StickyBox
Author
Callie Mao
Definition at line 9 of file StickyBox.java.
Constructor & Destructor Documentation
StickyBox.StickyBox (int xPos, int yPos, int xSize, int ySize, int speed, int movingXDirect, int movingYDirect, boolean stuck)
Definition at line 17 of file StickyBox.java.
Member Function Documentation
int StickyBox.getSpeed ()
Definition at line 81 of file StickyBox.java.
References mySpeed.
int StickyBox.getXDirection ()
Definition at line 55 of file StickyBox.java.
References xMove.
Referenced by BoxWorld.allowMovement(), BoxWorld.checkCollide(), and BoxWorld.updateSprites().
int StickyBox.getXPrev ()
Definition at line 47 of file StickyBox.java.
References xPrev.
Referenced by BoxWorld.allowMovement().
int StickyBox.getYDirection ()
Definition at line 59 of file StickyBox.java.
References yMove.
Referenced by BoxWorld.allowMovement(), BoxWorld.checkCollide(), and BoxWorld.updateSprites().
int StickyBox.getYPrev ()
Definition at line 51 of file StickyBox.java.
References yPrev.
Referenced by BoxWorld.allowMovement().
boolean StickyBox.isStuck ()
Definition at line 29 of file StickyBox.java.
void StickyBox.move ()
Definition at line 63 of file StickyBox.java.
Referenced by BoxWorld.updateSprites().
void StickyBox.setDirection (int x, int y)
Definition at line 37 of file StickyBox.java.
Referenced by BoxWorld.handleKeyInput(), BoxWorld.reset(), and BoxWorld.updateSprites().
void StickyBox.setPreviousDirection (int x, int y)
Definition at line 42 of file StickyBox.java.
Referenced by BoxWorld.reset(), and BoxWorld.updateSprites().
void StickyBox.setStuck (boolean stuck)
Definition at line 33 of file StickyBox.java.
Referenced by BoxWorld.updateSprites().
Member Data Documentation
boolean StickyBox.isStuck private
Definition at line 13 of file StickyBox.java.
Referenced by BoxWorld.updateSprites().
int StickyBox.mySpeed private
Definition at line 12 of file StickyBox.java.
Referenced by getSpeed().
int StickyBox.xMove private
Definition at line 10 of file StickyBox.java.
Referenced by getXDirection().
int StickyBox.xPrev private
Definition at line 14 of file StickyBox.java.
Referenced by getXPrev().
int StickyBox.yMove private
Definition at line 11 of file StickyBox.java.
Referenced by getYDirection().
int StickyBox.yPrev private
Definition at line 15 of file StickyBox.java.
Referenced by getYPrev().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_cym4/repository/StickyBox/src/StickyBox.java